# Generated by Django 4.2.6 on 2023-10-31 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, numbers, and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+\\- ]+$', 'Enter a valid username. This value may contain only letters, numbers, and @/./+/-/ space/_ characters.', 'invalid')], verbose_name='username'),
        ),
    ]
