# Generated by Django 4.2.6 on 2023-11-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
