# Generated by Django 4.2.6 on 2023-11-15 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(default='DefaultCity', max_length=150, verbose_name='City')),
                ('region', models.CharField(max_length=150, verbose_name='Region')),
                ('building_details', models.CharField(default='IRAQ', max_length=255, null=True, verbose_name='Building Details (Building/House Number, Floor, Apartment Number)')),
                ('street_details', models.CharField(max_length=255, verbose_name='Street Details (Street Name/Number)')),
                ('landmark', models.CharField(max_length=255, verbose_name='Landmark')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Mobile Phone Number')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='home', max_length=10, verbose_name='Address Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
