# Generated by Django 4.2.6 on 2023-11-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.AddField(
            model_name='address',
            name='Area',
            field=models.CharField(default='', max_length=150, verbose_name='Area'),
            preserve_default=False,
        ),
    ]
