# Generated by Django 4.2.6 on 2023-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_tag_product_rating_product_stock_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product_tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_tags', to='store.product'),
        ),
    ]
