# Generated by Django 4.2.6 on 2023-11-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product_tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tags', to='store.product'),
        ),
    ]
