# Generated by Django 4.2.6 on 2023-11-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_tag_product_tags_tag_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
