# Generated by Django 4.2.6 on 2023-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_category_banner_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
