# Generated by Django 4.2.6 on 2023-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productimage_image_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
