# Generated by Django 4.2.6 on 2023-11-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_delete_categoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_image',
        ),
    ]
