# Generated by Django 4.2.6 on 2023-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(default='images/category_images/default.png', help_text='Upload a category image', upload_to='images/category_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/products_images//default.png', help_text='Upload a product image', upload_to='images/products_images/', verbose_name='image'),
        ),
    ]
