# Generated by Django 4.2.6 on 2023-11-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_users_wishlist_delete_productuserwishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
