# Generated by Django 4.2.6 on 2023-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('processing_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
            ],
        ),
    ]
