# Generated by Django 4.2.6 on 2023-11-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_user_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
