# Generated by Django 4.2.6 on 2023-11-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
