# Generated by Django 4.2.6 on 2023-11-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_color_remove_order_size_orderitem_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
