# Generated by Django 4.2.6 on 2023-11-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=60),
        ),
    ]
