# Generated by Django 4.2.6 on 2023-11-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
    ]
