# Generated by Django 4.2.6 on 2023-11-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
